apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: donation-service
  namespace: solidarytech
spec:
  selector:
    matchLabels: { app: donation-service }
  endpoints:
    - port: http
      path: /metrics
      interval: 15s # scrape mais frequente no Hot Path - Golden Metrics do SLO precisam de granularidade
