apiVersion: v1
kind: ConfigMap
metadata:
  name: ngo-service-config
  namespace: solidarytech
data:
  PORT: "8081"
  ENVIRONMENT: "production"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
