apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ngo-service
  namespace: solidarytech
spec:
  selector:
    matchLabels: { app: ngo-service }
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
