apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cltcansado/solidarytech-gitops.git
    targetRevision: main
    path: observability/extras
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
